//! Real whisper.cpp transcription integration tests.
//!
//! These run the ACTUAL local Whisper pipeline (whisper-rs +
//! whisper.cpp + the cached ggml model) against the ElevenLabs voice
//! fixtures generated by `bun run e2e:fixtures`. No mocking — this is
//! the closest thing to "open the app and record a meeting" that can
//! run headlessly in CI.
//!
//! ## Requirements
//!   * The ggml model at the platform model dir
//!     (`~/Library/Application Support/Attune/models/ggml-large-v3.bin`
//!     on macOS). Override with `ATTUNE_WHISPER_MODEL`.
//!   * The WAV fixtures at `<repo>/e2e/fixtures/audio/*.wav`
//!     (run `bun run e2e:fixtures` once; ffmpeg transcodes the MP3s).
//!
//! When either is missing the tests **skip gracefully** (early
//! return + eprintln) so a CI box without the 3 GB model stays green.
//! On a developer machine with the model present they run for real.
//!
//! Large-v3 is slow (~10-30 s per clip), so the multi-language sweep
//! is marked `#[ignore]`. Run the full set explicitly:
//!
//!   cargo test -p attune-core --test transcription_fixtures -- --ignored --nocapture
//!
//! The fast default test transcribes a single English clip so
//! `cargo test` still exercises the path end-to-end without the full
//! multilingual cost.

use std::path::{Path, PathBuf};

use attune_core::transcription::local::LocalWhisperTranscriber;
use attune_core::transcription::Transcriber;

fn model_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("ATTUNE_WHISPER_MODEL") {
        let pb = PathBuf::from(p);
        return pb.is_file().then_some(pb);
    }
    // Default macOS app-support location used by the running app.
    let home = std::env::var_os("HOME")?;
    let pb = PathBuf::from(home)
        .join("Library/Application Support/Attune/models/ggml-large-v3.bin");
    pb.is_file().then_some(pb)
}

fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR is crates/attune-core; fixtures live at the
    // repo root under e2e/fixtures/audio.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../e2e/fixtures/audio")
}

fn wav(name: &str) -> Option<PathBuf> {
    let p = fixtures_dir().join(name);
    p.is_file().then_some(p)
}

/// Lowercase the transcript text concatenated across all segments.
fn transcript_text(t: &attune_core::transcription::Transcript) -> String {
    t.segments
        .iter()
        .map(|s| s.text.as_str())
        .collect::<Vec<_>>()
        .join(" ")
        .to_lowercase()
}

fn transcribe_fixture(file: &str, language_hint: Option<&str>) -> Option<attune_core::transcription::Transcript> {
    let Some(model) = model_path() else {
        eprintln!("SKIP: whisper model not found (set ATTUNE_WHISPER_MODEL or download via the app)");
        return None;
    };
    let Some(audio) = wav(file) else {
        eprintln!("SKIP: fixture {file} not found — run `bun run e2e:fixtures`");
        return None;
    };
    let t = LocalWhisperTranscriber::new(model)
        .with_threads(4)
        .transcribe(&audio, language_hint)
        .expect("transcription must not error");
    Some(t)
}

/// Fast default — one English clip, asserts the meeting keywords come
/// through. Proves the real pipeline works on every `cargo test`.
#[test]
fn english_business_clip_transcribes_with_expected_keywords() {
    let Some(t) = transcribe_fixture("en-business-1min.wav", Some("en")) else {
        return; // skipped — model / fixture absent
    };
    let text = transcript_text(&t);
    assert!(!text.trim().is_empty(), "transcript should not be empty");
    // The prompt mentions launch date, GTM, marketing, migration,
    // referral. Whisper won't be word-perfect, so we require a
    // majority of the strong content words to appear.
    let keywords = ["launch", "marketing", "migration", "referral"];
    let hits = keywords.iter().filter(|k| text.contains(**k)).count();
    assert!(
        hits >= 2,
        "expected >=2 of {keywords:?} in transcript, got {hits}.\nTranscript: {text}"
    );
}

/// English clinical clip — different voice + register. Asserts the
/// medical-consult vocabulary lands.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn english_clinical_clip_transcribes() {
    let Some(t) = transcribe_fixture("en-clinical-consult.wav", Some("en")) else {
        return;
    };
    let text = transcript_text(&t);
    let keywords = ["sleep", "medication", "side effects", "appetite", "nightmares"];
    let hits = keywords.iter().filter(|k| text.contains(**k)).count();
    assert!(hits >= 1, "expected clinical vocab in: {text}");
}

/// Language detection — the Turkish clip should be detected as
/// Turkish when no hint is given, and produce non-empty text.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn turkish_clip_detects_language_and_transcribes() {
    let Some(t) = transcribe_fixture("tr-meeting.wav", None) else {
        return;
    };
    let text = transcript_text(&t);
    assert!(!text.trim().is_empty(), "turkish transcript should not be empty");
    // whisper reports the detected language in `t.language`.
    if let Some(lang) = &t.language {
        assert_eq!(lang.to_lowercase(), "tr", "expected Turkish detection, got {lang}");
    }
}

/// German standup clip.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn german_clip_transcribes() {
    let Some(t) = transcribe_fixture("de-standup.wav", Some("de")) else {
        return;
    };
    assert!(!transcript_text(&t).trim().is_empty());
}

/// French pitch clip.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn french_clip_transcribes() {
    let Some(t) = transcribe_fixture("fr-product-pitch.wav", Some("fr")) else {
        return;
    };
    let text = transcript_text(&t);
    assert!(!text.trim().is_empty());
    // "Mac" is a proper noun that survives translation; a soft check.
    let keywords = ["mac", "transcription", "cloud"];
    assert!(
        keywords.iter().any(|k| text.contains(*k)),
        "expected one of {keywords:?} in: {text}"
    );
}

/// Spanish clinical follow-up clip.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn spanish_clip_transcribes() {
    let Some(t) = transcribe_fixture("es-clinical-followup.wav", Some("es")) else {
        return;
    };
    assert!(!transcript_text(&t).trim().is_empty());
}

/// Action-items clip — verifies names + ordinals come through, which
/// is what the extract-tasks agent downstream depends on.
#[test]
#[ignore = "slow: large-v3 ~15s; run with --ignored"]
fn action_items_clip_carries_assignees() {
    let Some(t) = transcribe_fixture("en-action-items.wav", Some("en")) else {
        return;
    };
    let text = transcript_text(&t);
    // Names from the prompt: Mira, Tony. Whisper may spell them
    // phonetically; require at least the action verbs.
    let verbs = ["draft", "confirm", "embargo", "wednesday", "thursday", "friday"];
    let hits = verbs.iter().filter(|k| text.contains(**k)).count();
    assert!(hits >= 2, "expected action vocab in: {text}");
}

#[test]
fn fixtures_and_model_presence_is_reported() {
    // A always-green diagnostic so the test output documents whether
    // the heavy tests actually ran or were skipped.
    let model = model_path();
    let fixture = wav("en-business-1min.wav");
    eprintln!(
        "transcription fixtures: model={} fixture={}",
        model.map(|p| p.display().to_string()).unwrap_or_else(|| "ABSENT".into()),
        fixture.map(|p| p.display().to_string()).unwrap_or_else(|| "ABSENT".into()),
    );
    // Also assert the fixtures directory exists at all (catches a
    // broken relative path).
    assert!(
        fixtures_dir().exists()
            || std::env::var("CI").is_ok(),
        "e2e/fixtures/audio dir not found at {}",
        fixtures_dir().display()
    );
}
