pub mod atomic_write;
pub mod chats;
pub mod decisions;
pub mod digest;
pub mod egress_log;
pub mod folders;
pub mod fs_io;
pub mod git_sync;
pub mod note_export;
pub mod retention;
pub mod search;
pub mod session;
pub mod settings;
pub mod share_bundle;
pub mod showcase;
pub mod snapshot;
pub mod spotlight;
pub mod tasks;
pub mod vault_layout;

pub use session::{scan_recordings, RecordingSummary};
pub use settings::{Settings, SettingsStore};
pub use tasks::{NewTask, Task, TaskStatus, TaskStore, TaskUpdate};
