// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * One agent's most recent run on a recording. Persisted as JSON.
 */
export type AgentRun = { agent_id: string, agent_name: string, provider: ProviderId, model: string, 
/**
 * The model's response text. Markdown is allowed and expected.
 */
response: string, 
/**
 * Set if the provider returned token usage.
 */
prompt_tokens: number | null, completion_tokens: number | null, 
/**
 * ISO-8601 timestamp the run finished at.
 */
finished_at: string, };
