// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read-only agent definition surfaced to the UI.
 */
export type Agent = { 
/**
 * Stable kebab-case identifier. Used as the filename for
 * persisted runs and as the route key in the UI.
 */
id: string, name: string, 
/**
 * One-sentence description shown under the agent's button.
 */
description: string, 
/**
 * The system prompt the model sees. Kept short — long prompts eat
 * the context budget and rarely help on transcripts of meetings.
 */
system_prompt: string, };
