// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

export type AgentRun = { agent_id: string, agent_name: string, provider: ProviderId, model: string, response: string, prompt_tokens: number | null, completion_tokens: number | null, finished_at: string, };
