// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceSpan } from "./EvidenceSpan";
import type { ProviderId } from "./ProviderId";
import type { ToolCallTrace } from "./ToolCallTrace";

export type AgentRunTelemetry = { agent_id: string, provider: ProviderId, model: string, latency_ms: bigint, prompt_tokens: number | null, completion_tokens: number | null,

total_tokens: number | null,

estimated_cost_usd: number | null, tool_calls: Array<ToolCallTrace>, evidence_spans: Array<EvidenceSpan>,

previous_response: string | null, finished_at: string, };
