// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export type AttendeeSuggestion = {

email: string,

display_name: string,

meeting_count: number, };
