// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GET-132 — a single teammate suggestion derived from recent
 * calendar events. Returned by `derive_attendee_suggestions` and
 * surfaced by the onboarding invite-teammates screen.
 */
export type AttendeeSuggestion = { 
/**
 * Email address as it appeared in the calendar attendee list.
 * Always lowercased.
 */
email: string, 
/**
 * Display name when EventKit knew one. Empty string when the
 * attendee entry only carried an email (the UI falls back to
 * the local part of the email in that case).
 */
display_name: string, 
/**
 * Number of distinct events in the input window where this
 * attendee appeared. Drives the "N meetings together" caption.
 */
meeting_count: number, };
