// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, title: string, location?: string | null, starts_at: string, ends_at: string, attendees?: Array<string>, conference_url?: string | null, notes?: string | null, };
