// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureArtifacts = { session_dir: string, mic_path: string | null, system_path: string | null, started_at: string, stopped_at: string, };
