// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * One channel's transcript inside a [`SessionTranscript`]. The
 * `channel` field is the same identifier used elsewhere ("mic" /
 * "system") so the UI can label it ("You" / "Others") consistently.
 */
export type ChannelTranscript = { 
/**
 * "mic" or "system" — the audio channel this transcript was
 * produced from.
 */
channel: string, language: string | null, segments: Array<TranscriptSegment>, };
