// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";


export type ChannelTranscript = {

channel: string, language: string | null, segments: Array<TranscriptSegment>, };
