// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageRec } from "./ChatMessageRec";

/**
 * A persisted conversation. `id` is client-generated so saves are
 * idempotent upserts. `scope` is "library" or "note"; note threads also
 * carry the `session_dir` they belong to.
 */
export type ChatThread = { id: string, scope: string, session_dir: string | null, title: string, created_at: string, updated_at: string, messages: Array<ChatMessageRec>, };
