// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRole } from "./ChatRole";

/**
 * One message in a chat conversation.
 */
export type ChatMessage = { role: ChatRole, content: string, };
