// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageRec } from "./ChatMessageRec";

export type ChatThread = { id: string, scope: string, session_dir?: string | null, title: string, created_at: string, updated_at: string, messages: Array<ChatMessageRec>, };
