// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation role. `Tool` carries the result of a tool invocation
 * back to the model in a follow-up turn.
 */
export type ChatRole = "system" | "user" | "assistant" | "tool";
