// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";

/**
 * A non-streaming chat response.
 */
export type ChatResponse = { text: string, finish_reason: FinishReason, prompt_tokens: number | null, completion_tokens: number | null, };
