// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRole } from "./ChatRole";
import type { ToolCall } from "./ToolCall";

export type ChatMessage = { role: ChatRole, content: string, tool_calls?: Array<ToolCall> | null, tool_call_id?: string | null, };
