// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation role. We intentionally do not model tool messages in
 * phase 1 — they arrive with tool dispatch in phase 9.
 */
export type ChatRole = "system" | "user" | "assistant";
