// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationKind } from "./CitationKind";

export type Citation = { id: string, kind: CitationKind, label: string, session_label: string | null, start_seconds: number | null, end_seconds: number | null, 
/**
 * Verbatim snippet — the LLM injects this into its system prompt
 * and the renderer also shows it under the citation chip.
 */
snippet: string, };
