// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Decision = { id: string, statement: string, rationale?: string | null, source_session_dir: string, source_session_label: string, evidence_span?: string | null, reversed_by_id?: string | null, decided_at: string, };
