// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { name: string, is_default: boolean, default_sample_rate: number | null, default_channels: number | null, };
