// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceDoc = { device_id: string, device_name: string, created_at: string, last_seen_at: string | null, user_agent: string | null, ip: string | null, };
