// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { name: string, is_default: boolean, 
/**
 * Default input sample rate reported by the device. May be `None` if
 * the device cannot be queried (rare).
 */
default_sample_rate: number | null, 
/**
 * Default input channel count reported by the device.
 */
default_channels: number | null, };
