// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export type DiarizationModelStatus = { id: string, label: string, path: string, present: boolean, bytes_on_disk: bigint | null, approx_total_bytes: bigint, };
