// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two ONNX models the diarization pipeline depends on. Variants
 * are stable identifiers used by `Settings.diarization` and the Tauri
 * command surface.
 */
export type DiarizationModel = "segmentation" | "embedding-resnet34-lm";
