// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DigestResult = { path: string, recordings: number, aged_tasks: number, new_memories: number, bytes: bigint, };
