// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EgressEntry = { id: string, emitted_at: string, endpoint: string, provider: string, bytes: bigint, recording_id: string, cost_usd: number, prev_sha256: string, };
