// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EgressEntry = { id: string, emitted_at: string, endpoint: string, provider: string, bytes: bigint, 
/**
 * Recording id this egress is associated with — empty when the
 * call doesn't belong to one (model download, key test).
 */
recording_id: string, cost_usd: number, 
/**
 * SHA-256 of the previous line in the chain; empty string for
 * the first entry.
 */
prev_sha256: string, };
