// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier the index column writes when persisting a row.
 */
export type EmbeddingModel = "openai-text-embedding-3-large" | "bge-small-en-v1.5" | "nomic-embed-text-v1.5";
