// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedModel } from "./CachedModel";

export type EvictSummary = { evicted: Array<CachedModel>, bytes_freed: bigint, remaining_bytes: bigint, };
