// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verbatim transcript span the agent grounded a claim in. Pair with
 * the locate_span helper (#038 / GET-41) to render a clickable jump.
 */
export type EvidenceSpan = {
/**
 * Human-readable label of what this evidence is for ("task: ship
 * the redesign", "memory: user.company"). Optional for free-form
 * agents.
 */
label: string | null, span_text: string, };
