// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a generation stopped. Mostly a courtesy for the UI; we always
 * surface the partial response either way.
 */
export type FinishReason = "stop" | "length" | "tool_call" | "error";
