// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitSyncSummary = {
/**
 * Was the directory a git repo at all? When false, every other
 * field is None / 0 / "" — the caller surfaces a hint to the
 * user instead of a sync result.
 */
is_repo: boolean,
/**
 * Branch the sync targeted.
 */
branch: string,
/**
 * stdout/stderr of the underlying git pull, useful for the
 * 'why did it fail' tooltip the UI shows on error.
 */
pull_log: string,
/**
 * Same for the push half.
 */
push_log: string,
/**
 * True when the commit step ran (i.e. the working tree had
 * uncommitted Attune-side changes worth pushing).
 */
committed: boolean,
/**
 * True when the whole flow completed end-to-end. False means
 * one of pull / commit / push failed; the user reads pull_log /
 * push_log to find out which.
 */
ok: boolean, };
