// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitSyncSummary = { is_repo: boolean, branch: string, pull_log: string, push_log: string, committed: boolean, ok: boolean, };
