// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InboxEntry = {

path: string,

name: string,

bytes: bigint,

modified_at: string, };
