// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InboxEntry = { 
/**
 * Absolute path on disk; the UI uses this both as a stable
 * React key and to surface 'reveal in Finder'.
 */
path: string, 
/**
 * The file's basename, with the `.json` extension stripped.
 */
name: string, 
/**
 * Bytes — useful when surfacing 'looks empty' empty-state
 * without re-reading the file.
 */
bytes: bigint, 
/**
 * Modified time as RFC-3339 (best effort; empty when the
 * platform doesn't supply it).
 */
modified_at: string, };
