// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteKind } from "./NoteKind";

export type LiveNote = {
/**
 * Recording-relative timestamp the note was anchored to.
 */
anchor_seconds: number, kind: NoteKind, text: string, };
