// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalLlmModel = "qwen25_7_b_instruct" | "llama31_8_b_instruct" | "phi35_mini" | "gemma2_2_b_it";
