// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds of memory a single-user meetings app needs. This is a
 * deliberate subset of Avid Brain's 10 event kinds (Observe / Claim /
 * Lesson / Pref / SkillEdit / Verify / Archive / Redact / Import /
 * Audit) — we don't need Lesson or SkillEdit yet, and Audit is
 * implicit in the supersede chain.
 *
 * - `Observe` — free-form context the model thought worth keeping
 *   ("user prefers async over sync standups").
 * - `Claim` — schema-typed fact addressable by `key`
 *   (`user.company` = "Attune"). Supersedes prior claims with the
 *   same key.
 * - `Pref` — user preference, also keyed and superseded
 *   (`ui.theme` = "dark").
 * - `Person` — someone the user mentions; `key` is the canonicalised
 *   handle ("ege", "alice-engineering"); `content` is the role + any
 *   other notes.
 */
export type MemoryKind = "observe" | "claim" | "pref" | "person";
