// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export type MemoryUpdate = { content: string | null, key: string | null, evidence: string | null, tags: Array<string> | null, pinned: boolean | null, };
