// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";


export type Memory = {

id: string, kind: MemoryKind,

key: string | null,

content: string,

evidence: string | null,

confidence: number,

tags: Array<string>,

source_session_dir: string | null,

source_session_label: string | null,

valid_from: string,

valid_until: string | null,

supersedes_id: string | null,

pinned: boolean, created_at: string, updated_at: string, };
