// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";

/**
 * Search/filter parameters. All fields are optional; the default
 * returns every currently-valid memory.
 */
export type MemoryQuery = {
/**
 * Free-text query string. Empty → no text filter (returns by
 * recency).
 */
query: string | null,
/**
 * Restrict to these kinds. Empty → all kinds.
 */
kinds: Array<MemoryKind>,
/**
 * When true, include superseded / soft-deleted memories.
 * Defaults to false (currently-valid only).
 */
include_archived: boolean,
/**
 * Max rows returned.
 */
limit: number | null, };
