// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static metadata about a provider's model.
 */
export type ModelInfo = { id: string, display_name: string, context_window: number, };
