// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloud model quality tier (GET-204).
 *
 * `Standard` maps to a fast, cheap model (gpt-4o-mini); `Premium` maps
 * to a capable reasoning model (gpt-4o or equivalent). The router picks
 * the tier automatically based on transcript complexity; the user can
 * override per-run or in Settings.
 */
export type ModelTier = "Standard" | "Premium";
