// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";

/**
 * Constructor payload for [`crate::memory::MemoryStore::create`].
 * Mirrors `NewTask` — the store generates id, timestamps, and
 * validity bounds.
 */
export type NewMemory = { kind: MemoryKind, key: string | null, content: string, evidence: string | null, confidence: number, tags: Array<string>, source_session_dir: string | null, source_session_label: string | null, };
