// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * Constructor payload for [`TaskStore::create`]. Everything except
 * the title is optional so the kanban's inline composer can create
 * a task with just a title and the `create_task` tool can omit any
 * field the model didn't pick up.
 */
export type NewTask = { title: string, status: TaskStatus | null, owner: string | null, due: string | null, notes: string | null, source_session_dir: string | null, source_session_label: string | null, agent_origin: boolean, };
