// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selectable enhanced-notes format surfaced to the UI.
 */
export type NoteTemplate = {
/**
 * Stable kebab-case identifier, stored in `template.txt`.
 */
id: string, name: string,
/**
 * One-line description for the picker.
 */
description: string, };
