// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteSearchHit = { session_dir: string, label: string, title?: string | null, snippet: string, matched_in: string, };
