// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionStatus = "not_determined" | "granted" | "denied" | "restricted" | "unknown";
