// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * Status of one provider for the Settings UI. Returned by
 * `list_providers` Tauri command.
 */
export type ProviderStatus = { id: ProviderId, display_name: string, 
/**
 * True if a key is present in the keychain.
 */
configured: boolean, 
/**
 * Last 4 characters of the stored key (e.g. "…AB12"), if any.
 */
redacted_suffix: string | null, 
/**
 * True if this provider is the one we recommend in onboarding.
 * Currently OpenAI per the vault plan.
 */
recommended: boolean, };
