// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * Non-secret configuration for a provider. The API key lives in the
 * keychain, not here.
 */
export type ProviderConfig = { provider: ProviderId, base_url: string, default_model: string, };
