// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for each provider we ship support for.
 *
 * Wire-encoded as lowercase ("openai", "anthropic", "deepseek") so
 * JSON files and keychain entries stay stable across renames in the
 * Rust source.
 */
export type ProviderId = "openai" | "anthropic" | "deepseek";
