// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

export type ProviderStatus = { id: ProviderId, display_name: string, configured: boolean, redacted_suffix: string | null, recommended: boolean, };
