// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurgeSummary = { sessions_inspected: number, wavs_deleted: number, bytes_freed: bigint,

failed: Array<string>, };
