// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurgeSummary = { sessions_inspected: number, wavs_deleted: number, bytes_freed: bigint, 
/**
 * Session directories that hit the predicate but failed to
 * delete (permission errors etc.). Each entry is the absolute
 * session_dir. Empty in the happy path.
 */
failed: Array<string>, };
