// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A raw editor line as the live-notes UI holds it: the verbatim text
 * (slash command included) plus the timestamp the line was anchored
 * to. This is the lossless round-trip shape persisted to disk so the
 * editor can repopulate on resume; [`parse_line`] turns it into the
 * grouped [`LiveNote`] shape only at render time.
 */
export type RawNoteLine = { text: string, anchor_seconds: number, };
