// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the current capture session, reported to the UI.
 */
export type RecordingStatus = { recording: boolean, elapsed_secs: bigint, channels: Array<string>, 
/**
 * Absolute path of the in-progress session directory, so the live
 * notes editor (GET-145) can autosave into it mid-recording. None
 * when idle.
 */
session_dir: string | null, 
/**
 * True when a note is open but capture is paused (GET-149): no
 * active session, but a Resume will continue into the same note.
 */
paused: boolean, };
