// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a saved recording session, as discovered on disk.
 */
export type RecordingSummary = { session_dir: string, label: string, duration_seconds: bigint, mic_bytes: bigint | null, system_bytes: bigint | null, mic_sample_rate: number | null, system_sample_rate: number | null, created_at: string | null, };
