// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingStatus = { recording: boolean, elapsed_secs: bigint, channels: Array<string>, session_dir: string | null, paused: boolean, mic_silent: boolean, needs_segment: boolean, };
