// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the current capture session, reported to the UI.
 */
export type RecordingStatus = { recording: boolean, elapsed_secs: bigint, channels: Array<string>, };
