// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureArtifacts } from "./CaptureArtifacts";

/**
 * Result of [`CaptureSession::stop`] in a form ready to hand to the UI:
 * the raw [`CaptureArtifacts`] plus a human-friendly label derived from
 * the session directory name.
 */
export type RecordingResult = { artifacts: CaptureArtifacts, label: string, };
