// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureArtifacts } from "./CaptureArtifacts";


export type RecordingResult = { artifacts: CaptureArtifacts, label: string, };
