// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReferralStats = { token: string, share_url: string, qualified_count: number, pending_count: number, free_months_earned: number, yearly_cap: number, yearly_remaining: number, };
