// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./ModelTier";

/**
 * Which extraction agents the router recommends running. The caller
 * AND-combines this with the user's own auto-run toggles.
 */
export type RouterDecision = { run_summarise: boolean, run_extract_tasks: boolean, run_extract_memories: boolean, run_find_decisions: boolean, run_autoname: boolean,
/**
 * Recommended cloud model tier for this recording (GET-204).
 * The caller may override with a user preference.
 */
model_tier: ModelTier, };
