// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouterPolicy = { voice_memo_max_secs: number, summarise_min_words: number, memories_min_words: number, decisions_min_participants: number, premium_tier_min_words: number, };
