// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./ModelTier";

export type RouterDecision = { run_summarise: boolean, run_extract_tasks: boolean, run_extract_memories: boolean, run_find_decisions: boolean, run_autoname: boolean, model_tier: ModelTier, };
