// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouterPolicy = {
/**
 * Below this many seconds the recording is a voice memo. Skip
 * task / decision extraction; keep summarise + autoname.
 */
voice_memo_max_secs: number,
/**
 * Below this many words we don't bother summarising — the user
 * can read the transcript in under 10s.
 */
summarise_min_words: number,
/**
 * Below this many words the memory pass is unlikely to find a
 * claim worth keeping (small-talk threshold).
 */
memories_min_words: number,
/**
 * Recordings with only one participating channel are monologues;
 * the decision-finder is built for back-and-forth. Skip on
 * monologues.
 */
decisions_min_participants: number, };
