// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelTranscript } from "./ChannelTranscript";

/**
 * Full per-session transcript: one [`ChannelTranscript`] per audio
 * channel that produced output. This is the shape that lives in
 * `<session_dir>/transcript.json` and the shape the frontend reads
 * and edits.
 */
export type SessionTranscript = { channels: Array<ChannelTranscript>, };
