// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted user settings.
 */
export type Settings = { mic_device: string | null, system_audio_enabled: boolean, output_dir: string, notes_dir: string, tasks_path: string, transcripts_dir: string, theme: string, transcriber: string, openai_api_key: string, transcription_language: string, dictionary_terms: Array<string>,
/**
 * Identifier of the local Whisper model the user has chosen (e.g.
 * "large-v3", "small"). Used only when `transcriber == "local_whisper"`.
 */
local_whisper_model: string,
/**
 * macOS only. When true, mic capture goes through Apple's Voice
 * Processing IO AudioUnit (AEC + noise suppression + AGC) so the
 * mic stops picking up speaker bleed when the user is not
 * wearing headphones. Falls back to the plain cpal path on
 * VPIO init failure. Ignored on non-macOS targets.
 */
voice_processing_enabled: boolean,
/**
 * When true, the app starts transcribing automatically as soon as
 * a recording is stopped. Honours the currently-selected
 * `transcriber` provider (OpenAI Whisper API requires
 * `openai_api_key`; Local Whisper needs no key). When false the
 * user transcribes manually from the Library row.
 */
auto_transcribe_enabled: boolean,
/**
 * When true and an AI provider key is configured, the app
 * automatically runs the `summarize` agent immediately after a
 * transcription completes. Lets the user stop a meeting and walk
 * away knowing the summary will be on the recording's page when
 * they come back. Falls back to a no-op when no AI key is set.
 */
auto_summarize_enabled: boolean,
/**
 * When true and an AI provider key is configured, the app
 * automatically runs the `extract-tasks` agent after a
 * transcription completes. The agent uses the `create_task`
 * tool to populate the kanban directly, so the user can stop a
 * meeting and come back to a populated to-do board. Skipped
 * silently if no AI key is set.
 */
auto_extract_tasks_enabled: boolean, };
