// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareBundleSummary = { destination: string, files: number, bytes: bigint,
/**
 * SHA-256 of the manifest contents, hex-encoded. The bundle's
 * fingerprint the recipient can quote in messages ("I sent you
 * share bundle abc123…").
 */
manifest_sha256: string, };
