// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShowcaseEntry } from "./ShowcaseEntry";

export type Showcase = { handle: string, display_name: string, bio: string, entries: Array<ShowcaseEntry>, };
