// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful export.
 */
export type SnapshotSummary = { destination: string, 
/**
 * Number of files inside the zip (not counting `manifest.json`).
 */
files: number, 
/**
 * Compressed size of the resulting zip in bytes.
 */
bytes: bigint, };
