// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakerLabel = { cluster: number, name: string | null, auto_named: boolean, has_embedding: boolean, suggested_name: string | null, suggested_score: number | null, };
