// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight, embedding-free view of a session speaker for the frontend.
 */
export type SpeakerLabel = { 
/**
 * Diarizer cluster id — matches `TranscriptSegment.speaker`.
 */
cluster: number, 
/**
 * User-facing name, when set; `null` falls back to "Speaker N" in the UI.
 */
name: string | null, 
/**
 * True when the name was filled by an automatic registry match.
 */
auto_named: boolean, 
/**
 * True when this cluster carries a usable voice embedding (i.e. it can
 * be remembered). False for clusters with too little audio.
 */
has_embedding: boolean, };
