// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GET-188. System-audio speech-enhancement settings. Nested so the two
 * knobs travel together and a future per-recording override has an
 * obvious home.
 */
export type SystemAudioEnhancement = { 
/**
 * Master toggle. Default `false` — experimental, A/B-gated.
 */
enabled: boolean, 
/**
 * Maximum attenuation the enhancer may apply, in dB (negative; more
 * negative = more aggressive). Default `-20.0`, a conservative cap
 * that trims obvious noise without flattening the spectral detail
 * Whisper and the speaker-embedding model depend on.
 */
atten_lim_db: number, };
