// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * Partial update sent through `update_task`. Each field is
 * `Option<Option<T>>` so the wire format can distinguish
 * "not present in the patch" (None) from "explicitly clear this
 * nullable field" (Some(None)) for nullable fields. For now we keep
 * it simple — `None` means "leave alone", `Some(value)` means set.
 * Setting a nullable field to None via update is uncommon enough
 * that we don't model "clear" separately; users delete the task
 * instead.
 */
export type TaskUpdate = { title: string | null, status: TaskStatus | null, owner: string | null, due: string | null, notes: string | null, };
