// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * A single to-do item. Always has an id + title + status; everything
 * else is optional metadata so the model can fill in what it knows
 * without us rejecting a tool call for a missing owner.
 */
export type Task = { 
/**
 * UUID v4 string. Generated server-side so the frontend can't
 * collide.
 */
id: string, title: string, status: TaskStatus, 
/**
 * Free-form owner ("Ege", "design team", "@alice"). The schema
 * does not enforce a particular handle format because meeting
 * transcripts use whatever conventions the speakers prefer.
 */
owner: string | null, 
/**
 * Free-form due date string. We don't parse this server-side —
 * the model produces "Friday", "next sprint", "2026-06-01" and
 * users type whatever they want. The kanban renders it as-is.
 */
due: string | null, 
/**
 * Optional extra context: "see point 3 in the deck", "blocked
 * on legal review", etc.
 */
notes: string | null, 
/**
 * Session directory of the recording this task was extracted
 * from. Lets the UI deep-link back to the editor and surface a
 * "see source" button. None for manually-created tasks.
 */
source_session_dir: string | null, 
/**
 * Human-readable label of the source recording (the trailing
 * component of session_dir) so we don't have to re-derive it in
 * every renderer.
 */
source_session_label: string | null, 
/**
 * True when an agent created this task via `create_task`. Lets
 * the UI mark agent-origin cards with a sparkle so the user can
 * scan the board and tell at a glance what came from a meeting.
 */
agent_origin: boolean, created_at: string, updated_at: string, };
