// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kanban column / lifecycle state of a task.
 */
export type TaskStatus = "todo" | "doing" | "done";
