// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, title: string, status: TaskStatus, owner: string | null, due: string | null, notes: string | null, source_session_dir: string | null, source_session_label: string | null, agent_origin: boolean, created_at: string, updated_at: string, };
