// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single tool invocation requested by the model.
 */
export type ToolCall = { 
/**
 * Provider-assigned id (e.g. OpenAI's `call_abc123`). Used to
 * pair the `Tool`-role response message back to the call.
 */
id: string, 
/**
 * Name of the tool the model wants to invoke. Must match a
 * `ToolDef.name` from the request.
 */
name: string, 
/**
 * JSON-encoded arguments string exactly as the model produced
 * it. We do not pre-parse here so the dispatcher can validate
 * and surface schema errors back to the model on the next turn.
 */
arguments: string, };
