// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export type ToolCallTrace = { tool: string,

arguments_json: string,

result: string, latency_ms: bigint, };
