// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool the agent invoked. The UI expands these inline under the
 * run-card so the user can see exactly what `create_task` etc. was
 * called with.
 */
export type ToolCallTrace = { tool: string,
/**
 * JSON-encoded arguments the model passed. We keep the original
 * string (not a serde_json::Value) so the UI can render it
 * verbatim without re-pretty-printing.
 */
arguments_json: string,
/**
 * Free-form result string the tool produced (the same value the
 * model receives back in the loop).
 */
result: string, latency_ms: bigint, };
