// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTranscript } from "./SessionTranscript";

export type TranscriptionResult = { session_dir: string, transcript_path: string, session_transcript: SessionTranscript, };
