// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptSegment = { start_seconds: number, end_seconds: number, text: string, speaker: number | null, language: string | null, };
