// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * A full transcript: the ordered sequence of segments and the language
 * the backend identified.
 */
export type Transcript = { language: string | null, segments: Array<TranscriptSegment>, };
