// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transcript } from "./Transcript";

/**
 * Outcome of a transcription run: the transcript itself plus the
 * session it belongs to and the on-disk JSON it was persisted to.
 */
export type TranscriptionResult = { session_dir: string, transcript_path: string, transcript: Transcript, };
