// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTranscript } from "./SessionTranscript";

/**
 * Outcome of a transcription run: the per-channel transcripts plus
 * the session they belong to and the on-disk JSON they were
 * persisted to.
 */
export type TranscriptionResult = { session_dir: string, transcript_path: string, session_transcript: SessionTranscript, };
