// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signals extracted from the transcript that the rules act on.
 */
export type TranscriptSignals = { duration_secs: number, word_count: number, participants: number, };
