// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * A full transcript for a single audio channel: the ordered sequence
 * of segments and the language the backend identified. This is the
 * shape each individual whisper run produces, before we attach a
 * channel name to it.
 */
export type Transcript = { language: string | null, segments: Array<TranscriptSegment>, };
