// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptHit = { channel: string, segment_index: number, start_seconds: number, end_seconds: number, matched_text: string, };
