// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-side user document (the parts the client cares about).
 */
export type UserDoc = { id: string, email: string, display_name: string | null, privacy_tier: string | null, subscription_tier: string | null, };
