// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cached identity surfaced to the UI between launches so the user
 * doesn't see "Signed in as ?" while the access token is being
 * refreshed.
 */
export type UserIdentity = { user_id: string, email: string, display_name: string | null, 
/**
 * Tier-1 or Tier-2 — read from the wire response so the UI can
 * reflect the encryption mode in the privacy band.
 */
privacy_tier: string | null, };
