// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verdict the guard emits per item.
 */
export type Verdict = "verified" | "low_confidence" | "not_grounded";
