// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export type WebhookEvent = "recording_finished" | "transcript_ready" | "task_created" | "memory_created";
