// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the GGML model variants whisper.cpp publishes. Sizes are the
 * approximate on-disk size of the .bin file.
 */
export type WhisperModel = "tiny" | "base" | "small" | "medium" | "large-v3";
