// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On-disk status of a model file. Carries the path even when the file
 * is missing so callers can show "would be downloaded to <path>".
 */
export type WhisperModelStatus = { id: string, path: string, present: boolean, bytes_on_disk: bigint | null, approx_total_bytes: bigint, };
